const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('index.html','utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
new vm.Script(script);
assert(!/sisCartIds|sisCartSyncVersion|很好|期末很简单|已注册|chatgpt\.site|metadataBase|personalNotes/.test(html));
assert(/https:\/\/sis\.cuhk\.edu\.cn/.test(html));
const controls={};
const context=vm.createContext({document:{querySelector:s=>controls[s]??={checked:false,value:20,dataset:{}}},localStorage:{setItem(){}},setTimeout(){},window:{}});
vm.runInContext(script.slice(0,script.lastIndexOf('try{const stored=')),context);
vm.runInContext(`render=()=>{};save=()=>{};flash=()=>{};
 if(courses.length!==31)throw Error('course count');
 if(courses.some(c=>!c.room||!c.campus))throw Error('missing location');
 selected=[];add('6104-4494');add('6104-4494');if(selected.length!==1)throw Error('duplicate');
 add('6104-4495');if(selected.join()!=='6104-4495')throw Error('switch');
 selected=['6101-4490','6116-4503'];add('6101-4491');if(selected.join()!=='6101-4490,6116-4503')throw Error('rejected switch lost course');
 selected=[];$('#noMorning').checked=true;$('#strict').checked=true;add('6101-4490');if(selected.length)throw Error('morning restriction');
 if(courses.find(c=>c.section==='4706').campus!=='西丽')throw Error('campus');
 if(courses.find(c=>c.code==='FIN6120').type!=='elective')throw Error('elective classification');
 `,context);
console.log('PASS: syntax, privacy, locations, duplicates, switching, conflict rejection, morning constraint.');
